baseURL = 'https://jf-chen.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = "hugo-theme-stack"

# 发布目录设置为 `docs`（GitHub Pages 支持从 `docs` 目录部署）
publishDir = "docs"
	
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
	
