baseURL = 'https://jf-chen.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = "hugo-theme-stack"

# 发布目录设置为 `docs`（GitHub Pages 支持从 `docs` 目录部署）
publishDir = "docs"

# 主题配置示例（根据主题文档自定义）
[params]
  # 主题相关配置，参考主题文档
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/jf-chen"
	
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3